app = "hadhara-university"  # You'll need to change this to a unique name
primary_region = "iad"  # US East (Virginia)

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[mounts]]
  source = "university_data"
  destination = "/data"

[env]
  NODE_ENV = "production"
  PORT = "8080"
